/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/computer.glb 
Author: Urpo (https://sketchfab.com/Urpo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-computer-f844c0357d284fd8baa1435e9ff31bb2
Title: Retro computer
*/

import { useFrame } from '@react-three/fiber'
import { useGLTF, Float, PresentationControls } from '@react-three/drei'
import * as THREE from 'three'

export default function Retro({ screenControl, ...props }) {
  const { nodes, materials } = useGLTF('/computer.glb')

  return (
    <PresentationControls
      global={false}
      cursor={true}
      snap={true}
      speed={1.5}
      polar={[-0.1, 0.2]}
      azimuth={[-0.5, 0.5]}
    >

      <group {...props} dispose={null}
        onClick={(e) => {
          e.stopPropagation();
          if (screenControl) screenControl("on");
        }}
        onPointerOver={() => { document.body.style.cursor = 'pointer' }}
        onPointerOut={() => { document.body.style.cursor = 'auto' }}
      >
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Part2} />
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Part1} />
          </group>
        </group>
      </group>

    </PresentationControls>
  )
}

useGLTF.preload('/computer.glb')