/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/computer.glb 
Author: Urpo (https://sketchfab.com/Urpo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-computer-f844c0357d284fd8baa1435e9ff31bb2
Title: Retro computer
*/

import { useEffect } from 'react'
import { useGLTF, Center } from '@react-three/drei'
import * as THREE from 'three'
import { useAudioManager } from '../Sounds'

export default function Retro({ screenControl, audio, ...props }) {
  const { nodes, materials } = useGLTF('/computer.glb')
  const { playPowerOn, computerBoot } = useAudioManager();

  useEffect(() => {
    Object.values(materials).forEach((material) => {
      material.transparent = false;
      material.opacity = 1;
      material.depthWrite = true;
      // THREE.DoubleSide forces the engine to draw the inside of the box as well
      material.side = THREE.DoubleSide;
      material.needsUpdate = true;
    });
  }, [materials]);

  const handleScreenClick = (e) => {
    e.stopPropagation();
    if (screenControl) { screenControl("on"); audio.playPowerOn(); audio.computerBoot() }
  }
  return (


    <group {...props} dispose={null}
      onClick={handleScreenClick}
      onPointerOver={() => { document.body.style.cursor = 'pointer' }}
      onPointerOut={() => { document.body.style.cursor = 'auto' }}
    >
      <Center>

        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Part2} />
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Part1} />
          </group>
        </group>
      </Center>
    </group>
  )
}

useGLTF.preload('/computer.glb')